//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kitaplik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitap
    {
        public int Id { get; set; }
        public string KitapAd { get; set; }
        public string SayfaSayisi { get; set; }
        public string Yazari { get; set; }
        public Nullable<int> KategoriId { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
